services:
  minecraft:
    image: sapmachine:latest
    ports:
      - "25565:25565"
    volumes:
      - ./:/app
    container_name: minecraft
    command: sh -c 'cd /app; java -Xmx2048M -Xms1024M -jar minecraft_server.1.21.4.jar nogui'
    stdin_open: true
    tty: true